language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
install:
  - composer install --dev
script: vendor/bin/phing
